# Generated by Django 3.2.5 on 2021-07-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210731_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='closest_point',
            field=models.CharField(default='(0,0)', max_length=100),
        ),
    ]
